/// Flutter icons LnAirboxIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LnAirboxIcons
///      fonts:
///       - asset: fonts/LnAirboxIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class LnAirboxIcons {
  LnAirboxIcons._();

  static const _kFontFam = 'LnAirboxIcons';

  static const IconData more_horiz = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_chevron_down = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_eye_invisible = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_eye_visible = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_check = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_chevron_left = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_search = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ic_pressure = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ic_humidity = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ic_co2 = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData ic_temperature = IconData(0xe80a, fontFamily: _kFontFam);
}
